services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
       REACT_APP_DB_HOST : ${REACT_APP_DB_HOST}
       REACT_APP_DB_USER :  ${REACT_APP_DB_USER}
       REACT_APP_DB_PASSWORD : ${REACT_APP_DB_PASSWORD}
       REACT_APP_DB_NAME : ${REACT_APP_DB_NAME}
       REACT_APP_API_KEY : ${REACT_APP_API_KEY}
       REACT_APP_JWT_SECRET : ${REACT_APP_JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "node", "ServerApp.js"]

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${REACT_APP_DB_PASSWORD}
      MYSQL_DATABASE: ${REACT_APP_DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/db/database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
